# Generated by Django 6.0.4 on 2026-05-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='tiene_doble_salto',
            field=models.BooleanField(default=False),
        ),
    ]
