# Generated by Django 6.0.4 on 2026-05-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_jugador_tiene_doble_salto'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='habilidades_equipadas',
            field=models.TextField(default=''),
        ),
    ]
