# Generated by Django 6.0.4 on 2026-05-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_jugador_habilidades_equipadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='nivel_desbloqueado',
            field=models.IntegerField(default=1),
        ),
    ]
