# Generated by Django 6.0.4 on 2026-05-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_jugador_nivel_desbloqueado'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='contrasena',
            field=models.CharField(default='', max_length=128),
        ),
    ]
