# Generated by Django 6.0.4 on 2026-05-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_jugador_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='tiene_dash',
            field=models.BooleanField(default=False),
        ),
    ]
