# Generated by Django 6.0.4 on 2026-05-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_jugador_tiene_dash'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='tiene_fuego',
            field=models.BooleanField(default=False),
        ),
    ]
