# Generated by Django 6.0.4 on 2026-05-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_jugador_tiene_fuego'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='tiene_escudo',
            field=models.BooleanField(default=False),
        ),
    ]
