# Generated by Django 6.0.4 on 2026-05-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_jugador_tiene_escudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='tiene_planeador',
            field=models.BooleanField(default=False),
        ),
    ]
