# Generated by Django 6.0.4 on 2026-05-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_jugador_tiene_planeador'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='tiene_agua',
            field=models.BooleanField(default=False),
        ),
    ]
